server:
  port: 9000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    minIdle: 10
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j

master:
  datasource:
    url: jdbc:mysql://192.168.10.181:3306/military_qa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: wgdb
    password: wgdb%2021
    driverClassName: com.mysql.cj.jdbc.Driver

cluster:
  datasource:
    url: jdbc:mysql://192.168.10.181:3306/zbzs1?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: wgdb
    password: wgdb%2021
    driverClassName: com.mysql.cj.jdbc.Driver


